services:
  imagedb:
    build: .
    container_name: imagedb
    ports:
      - "3001:3000"
    env_file:
      - path: .env
        required: false
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ARKIV_RPC_URL=https://kaolin.hoodi.arkiv.network/rpc
      - ARKIV_WS_URL=wss://kaolin.hoodi.arkiv.network/rpc/ws
      - ARKIV_CHAIN_ID=60138453025
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped